# Generated by Django 2.2 on 2019-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=50)),
                ('tweet', models.TextField()),
                ('date', models.DateField()),
                ('favCount', models.IntegerField()),
            ],
            options={
                'unique_together': {('screen_name', 'tweet')},
            },
        ),
    ]
