# Generated by Django 2.2 on 2019-06-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterdata',
            name='org_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='profile_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='tweet_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
